### ISSUE TITLE
Issues building ai

### ISSUE THREAD

**Issue by ghost** [danieltan1517/chess-jai#1]
This may be a Windows-only issue. I compiled (on jai beta 0.1.038) with "jai build.jai -- ai" and got the following:

```
In Workspace 4 ("ceij"):
C:/Users/Human/Downloads/chess-jai-master/search.jai:155,3: Error: Too many arguments: Wanted 4, got 5.

    negamax :: (chess: *ChessGame, depth: int, alpha: int, beta: int, fifty: int) -> int {
      read_input(chess.main_thread, nodes_searched, chess.maxnodes, time_begin, chess.movetime);

C:/Users/Human/Downloads/chess-jai-master/windows.jai:173,15: Info: ... Here is the procedure being called.

    read_input :: (nodes: int, maxnodes: int, time_begin: float64, movetime: int) #expand {
```

Looks like a simple fix. I may look at it later unless you have it done already. Thanks for sharing this amazing creation of yours, Daniel!

**Comment by danieltan1517** [comment]
I looked at this issue, and wrote a quick fix to this problem. The code should be theoretically okay, but on my Surface Pro, I get an Internal compiler error.

**Comment by danieltan1517** [comment]
The Internal Compiler Error seems to be a compiler bug on Jon's end, and I don't think I can fix the problem on my end. I reported the bug to Jon, but he hasn't responded to me.

**Comment by danieltan1517** [comment]
After a serious investigation into the compiler bug, I found a quick workaround. Everything should be running fine on windows now.
